coder/envbox

- .github/workflows/ci.yaml
- This lets Trivy run against the main branch.
> chore: run build job on main

- cli/clitest/fs.go
- cli/docker.go
- dockerutil/container.go
- dockerutil/container_test.go
- xunix/sys.go
- xunix/sys_test.go
Fixes https://github.com/coder/envbox/issues/28
- No longer fails when trying to copy outer container quota to inner container.
Warns in buildlog instead.
- Adds logic to determine current cgroup from /proc/self/cgroup
- Adds logic to read cpu.max from /sys/fs/cgroup/<self>/cpu.max
- Adds logic to write cpu.max to /sys/fs/cgroup/docker/<containerid>/init.scope/cpu.max
- Adds more unit tests around all of the above for both cgroupv1 and cgroupv2
Tested on:
- Rocky 9.1, kernel 5.14.0-162.23.1.el9_1.x86_64
- k3s v1.26.4
- Coder v0.23.2
Tested with both `systemd.unified_cgroup_hierarchy=1` and `systemd.unified_cgroup_hierarchy=0`.
You can test yourself with the envbox image `gcr.io/coder-dev-1/coder-cian/envboxv2:pr34`
> fix(envbox): work with cgroupv2

- cli/docker_test.go
- dockerutil/client.go
Needs to be base64url according to the [Docker docs](https://docs.docker.com/engine/api/v1.42/#section/Authentication)
Tested with CODER_INNER_IMAGE set to image hosted in a registry behind basic auth that has some funky characters in the password like `~` and `.`.
Before: envbox (ghcr.io/coder/envbox:5ef860c) image pull fails with following error: 
```
{"ts":"2023-07-06T16:53:24.81088446Z","level":"DEBUG","msg":"child log","caller":"/home/runner/work/envbox/envbox/background/process.go:248","func":"github.com/coder/envbox/background.scanIntoLog","logger_names":["dockerd"],"fields":{"process":"dockerd","content":"time=\"2023-07-06T16:53:24.810799902Z\" level=debug msg=\"Trying to pull registry.c3s.int.sporc.space/enterprise-base from https://registry.c3s.int.sporc.space\""}} …
```
> fix(dockerutil): use base64url for auth config encoding

- .github/workflows/ci.yaml
- .github/workflows/release.yaml
- deploy/Dockerfile
- dockerutil/image.go
The problem with the integration tests was an incompatibility between Docker and Go `1.20.6` so this also pins Go to `1.20.5` (temporarily).
> chore: pin docker version to avoid incompatibilities

- cli/cliflag/cliflag.go
- integration/docker_test.go
- integration/integrationtest/docker.go
- Fixed an issue where large integers CLI arguments were not parsed correctly
- Added an integration test to validate CPU/memory are set correctly in
the inner container.
> chore: test memory limits are being set on inner container

- cli/docker.go
- cli/docker_test.go
Currently the `CODER_AGENT_SUBSYSTEM` env var passed to the inner container is always set to `envbox` regardless of the parent value. This will pass the parent value if it's set and append `envbox` to it, ensuring that `envbox` isn't already there.
> fix: passthrough subsystem env vars

- README.md
Adds a note about the required structure of `.dockerconfigjson` if you're generating it using external tooling.
> chore(README.md): add note regarding structure of CODER_IMAGE_PULL_SECRET

- .github/workflows/release.yaml
- Makefile
- deploy/Dockerfile
- deploy/files/etc/apt/sources.list.d/docker.list
> chore: support arm builds

- .github/workflows/ci.yaml
https://github.com/coder/envbox/actions/runs/9764876997/job/26954239536#step:6:8
alternatively, we just tag with the git SHA and don't include the latest tag
> ci: fetch tags in order to get version

- .github/workflows/release.yaml
- We don't backport fixes so this should be fine.
> fix: fix release to push to latest

- .github/workflows/latest.yaml
- .github/workflows/release.yaml
- Don't automatically promote 'latest' tag
> feat: add workflow for promoting 'latest' docker tag

- cli/clitest/cli.go
- cli/clitest/fake.go
- cli/docker.go
- dockerutil/image.go
- dockerutil/registry.go
- dockerutil/registry_test.go
- integration/docker_test.go
- integration/integrationtest/coder.go
- integration/integrationtest/docker.go
- xunix/xunixfake/fs.go
This is the second part of the delivery that provides support for copying certs into the directory `dockerd` checks when pulling an image from a registry.
> feat: add support for copying certs to dockerd's registry directory

- cli/docker.go
- cli/docker_test.go
- dockerutil/client.go
- dockerutil/client_test.go
- integration/docker_test.go
- integration/integrationtest/docker.go
This PR fixes authentication not working if `Username, Password` fields are omitted in favor of an `Auth` field. The `Auth` field can be a base64 encoded concatenation of the two. This PR also adds logic to existing integration tests to ensure authenticated pulls work as expected.
fixes https://github.com/coder/envbox/issues/102
> fix: parse image auth config correctly

- Makefile
- README.md
- integration/docker_test.go
- xunix/gpu.go
- xunix/gpu_test.go
Relates to https://github.com/coder/envbox/issues/111
Container runtimes like the NVIDIA container toolkit will inject library dependencies inside containers they create. More recent versions of these runtimes / operators appear to mount the libraries with `$library.so.$NVIDIA_DRIVER_VERISON` and symlink `$library.so` to those locations.
Example:
```
lrwxrwxrwx  1 root root       32 Jan 26 20:09 libnvidia-allocator.so.1 -> libnvidia-allocator.so.550.90.07
-rwxr-xr-x  1 root root   168776 Dec 23 16:41 libnvidia-allocator.so.550.90.07
lrwxrwxrwx  1 root root       26 Jan 26 20:09 libnvidia-cfg.so.1 -> libnvidia-cfg.so.550.90.07
-rwxr-xr-x  1 root root   398968 Dec 23 16:41 libnvidia-cfg.so.550.90.07
-rwxr-xr-x  1 root root 43659040 Dec 23 16:41 libnvidia-gpucomp.so.550.90.07
lrwxrwxrwx  1 …
```
> fix(xunix): also mount shared symlinked shared object files

- dockerutil/image.go
- dockerutil/image_linux_amd64.go
- dockerutil/image_linux_arm64.go
Fixes an error in the definition of `usrLibMultiarchDir` in #127
> fix(dockerutil): correct usrLibMultiarchDir

- integration/gpu_test.go
- integration/integrationtest/docker.go
- xunix/gpu.go
- xunix/gpu_test.go
This PR fixes some issues Bjorn found when testing the changes in #127 as well as some other lingering issues I'd noticed:
1) The nvidia container runtime will mount libraries with the driver version number appended to them, and creates symlinks to those files:
```
root@ad0724e97635:/# ls -l /usr/lib/x86_64-linux-gnu/ | grep -Ei 'libgl|nvidia|vulkan|cuda'
lrwxrwxrwx  1 root root       12 Mar  6 23:19 libcuda.so -> libcuda.so.1
lrwxrwxrwx  1 root root       20 Mar  6 23:19 libcuda.so.1 -> libcuda.so.550.90.07
-rwxr-xr-x  1 root root 28581024 Dec 23 16:41 libcuda.so.550.90.07
lrwxrwxrwx  1 root root       28 Mar  6 23:19 libcudadebugger.so.1 -> libcudadebugger.so.550.90.07
-rwxr-xr-x  1 root root 10524136 Dec 23 16:41 libcudadebugger.so.550.90.07
lrwxrwxrwx  1 root root       32 Mar  6 …
```
> fix(xunix): improve handling of gpu library mounts

- .github/workflows/ci.yaml
- Support for 20.04 ends on 04/15/25.
> chore: update runners to Ubuntu 22.04

- dockerutil/client.go
- integration/docker_test.go
- https://github.com/coder/envbox/pull/103 introduced a hostname requirement in the auth config provided. This subtly broke some users.
> fix: provide backwards compatibility for image secrets without a hostname

- integration/integrationtest/docker.go
> chore: move all images to new GCP project

- .github/workflows/release.yaml
- Makefile
- deploy/Dockerfile
In particular, to capture Fix bug causing failure to open /proc/sys/kernel/shm inside Sysbox container (issues https://github.com/nestybox/sysbox/issues/903, https://github.com/nestybox/sysbox/issues/909). which is a blocker to running Oracle DB images.
> Sysbox 0.6.7
